import Head from 'next/head'
import Layout from '../components/landingpage/utils/layout'
import Featured from '../components/landingpage/utils/featured'
import Offer from '../components/landingpage/utils/offer'
import TrendProduct from '../components/landingpage/product/trendproduct'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Featured/>
        <Offer/>
        <TrendProduct/>
      </Layout>
    </>
  )
}
